### model
model_name_or_path: /data/xiaoyukou/ckpts/Qwen2-7B-Instruct
quantization_bit: 4

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: AssetGeneration_train
template: qwen
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen/fsdp_qlora_sft/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 20
gradient_accumulation_steps: 2
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
bf16: true    # must be true for fsdp_qlora_sft
ddp_timeout: 180000000

### eval
val_size: 0.002
per_device_eval_batch_size: 30
evaluation_strategy: steps
eval_steps: 500
