### model
model_name_or_path: /scratch/workspaceblobstore/users/xiaoyukou/ckpts/Qwen3.5-9B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset: shopping_journey_w_query_gen
template: qwen3_5_nothink
cutoff_len: 20000
max_samples: 2000000
overwrite_cache: true
preprocessing_num_workers: 40
tokenized_path: /cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Results_journey_w_query/qwen3-5-9b_full/tokenized_dataset
dataloader_num_workers: 8

### output
output_dir: /cosmos/projects/Recommendations/PartnerData/Pipelines/OneRec/Results_journey_w_query/qwen3-5-9b_full/
logging_steps: 20
save_steps: 40
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 12
gradient_accumulation_steps: 2
learning_rate: 5.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
packing: true
enable_liger_kernel: true
#group_by_length: true

### eval
#val_size: 0.001
#per_device_eval_batch_size: 8
#eval_strategy: steps
#eval_steps: 1000
