### model
model_name_or_path: /data/xiaoyukou/ckpts/Ministral-8B-Instruct-2410
quantization_bit: 4
quantization_method: bitsandbytes  # choices: [bitsandbytes (4/8), hqq (2/3/4/5/6/8), eetq (8)]

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: AssetGeneration_train_add_copilot_10-25
template: mistral
cutoff_len: 1024
max_samples: 2000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/Ministral/fsdp_qlora_sft_add_copilot_10-25/
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 12
gradient_accumulation_steps: 2
learning_rate: 0.0001
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true    # must be true for fsdp_qlora_sft
ddp_timeout: 180000000

### eval
val_size: 0.005
per_device_eval_batch_size: 15
evaluation_strategy: steps
eval_steps: 500
