### model
model_name_or_path: /data/xiaoyukou/alignment-handbook/ckpts/Mistral-7B-Instruct-v0.2

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: q_proj,v_proj,k_proj,o_proj,gate_proj,up_proj,down_proj
lora_rank: 16
lora_dropout: 0.05

### dataset
dataset: AssetGeneration_train
template: mistral
cutoff_len: 1024
max_samples: 500000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/mistral/lora_sft
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
learning_rate: 0.0002
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_steps: 0.1
fp16: true

### eval
val_size: 0.01
per_device_eval_batch_size: 32
evaluation_strategy: steps
eval_steps: 100
